---
- name: Ensure firewall rule is in place for site
  win_firewall_rule:
      name: Globomantics
      enabled: yes
      state: present
      localport: 8080
      action: allow
      direction: in
      protocol: tcp

- name: Ensure firewall rule is in place for http
  win_firewall_rule:
      name: Globomantics http test
      enabled: yes
      state: present
      localport: 80
      action: allow
      direction: in
      protocol: tcp